USE [TimeTracker]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- Time reportings
IF OBJECT_ID (N'TimeReportings', N'U') IS NULL 
BEGIN
	CREATE TABLE [dbo].[TimeReportings](
		[Id] INT IDENTITY(1,1) NOT NULL,	
		[Name] NVARCHAR(50) NOT NULL
CONSTRAINT [PK_TimeReportings] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)	
END
GO

-- AFEs
IF OBJECT_ID (N'Afes', N'U') IS NULL 
BEGIN
	CREATE TABLE [dbo].[Afes](
		[Id] INT IDENTITY(1,1) NOT NULL,	
		[Name] NVARCHAR(20) NOT NULL
CONSTRAINT [PK_Afes] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)	
END
GO

-- Projects
IF OBJECT_ID (N'Projects', N'U') IS NULL 
BEGIN
	CREATE TABLE [dbo].[Projects](
		[Id] INT IDENTITY(1,1) NOT NULL,	
		[Comments] NVARCHAR(MAX) NOT NULL,
		[TimeReportingId] INT NOT NULL,
		[AfeId] INT NOT NULL,
		[LogTime] DATETIME NULL,
		[ManualEntryStart] DATETIME NULL,
		[ManualEntryEnd] DATETIME NULL,
CONSTRAINT [PK_Projects] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)	

ALTER TABLE [dbo].[Projects] WITH CHECK ADD CONSTRAINT [FK_Projects_TimeReportings_TimeReportingId] FOREIGN KEY([TimeReportingId])
REFERENCES [dbo].[TimeReportings] ([Id])

ALTER TABLE [dbo].[Projects] WITH CHECK ADD CONSTRAINT [FK_Projects_Afes_AfeId] FOREIGN KEY([AfeId])
REFERENCES [dbo].[Afes] ([Id])

END
GO

-- Users
IF OBJECT_ID (N'Users', N'U') IS NULL 
BEGIN
	CREATE TABLE [dbo].[Users](
		[Id] INT IDENTITY(1,1) NOT NULL,	
		[Name] NVARCHAR(50) NOT NULL,
		[LastLoginDate] DATETIME NULL
CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)	

END
GO

-- User Photos
IF OBJECT_ID (N'UserPhotos', N'U') IS NULL 
BEGIN
	CREATE TABLE [dbo].[UserPhotos](
		[Id] INT NOT NULL,	
		[FileName] NVARCHAR(255) NOT NULL,
		[MimeType] NVARCHAR(255) NOT NULL,
		[UserId] INT NOT NULL,
CONSTRAINT [PK_UserPhotos] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)	

ALTER TABLE [dbo].[UserPhotos] WITH CHECK ADD CONSTRAINT [FK_UuserPhotos_Users_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([Id])

END
GO

-- User settings
IF OBJECT_ID (N'UserSettings', N'U') IS NULL 
BEGIN
	CREATE TABLE [dbo].[UserSettings](
		[Id] INT IDENTITY(1,1) NOT NULL,			
		[UserId] INT NOT NULL,
		[CostCenterId] NVARCHAR(20) NULL,
		[DateFormat] NVARCHAR(20) NOT NULL,
		[Is12HourFormat] BIT NOT NULL
CONSTRAINT [PK_UserSettings] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)	

ALTER TABLE [dbo].[UserSettings] WITH CHECK ADD CONSTRAINT [FK_UserSettings_Users_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([Id])

	-- Default value for DateFormat column
	ALTER TABLE [dbo].[UserSettings]
		ADD CONSTRAINT DF_UserSettings_DateFormat
		DEFAULT N'dd-mm-yyyy' FOR [DateFormat] 

	-- Default value for Is24HourFormat column
	ALTER TABLE [dbo].[UserSettings]
		ADD CONSTRAINT DF_UserSettings_Is12HourFormat
		DEFAULT 0 FOR [Is12HourFormat] 

END
GO



/*

-- Makers
IF OBJECT_ID (N'Makers', N'U') IS NULL 
BEGIN
	CREATE TABLE [dbo].[Makers](
		[Id] INT IDENTITY(1,1) NOT NULL,	
		[Name] NVARCHAR(50) NOT NULL
CONSTRAINT [PK_Makers] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)	
END
GO

-- Models
IF OBJECT_ID (N'Models', N'U') IS NULL 
BEGIN
	CREATE TABLE [dbo].[Models](
		[Id] INT IDENTITY(1,1) NOT NULL,	
		[Name] NVARCHAR(50) NOT NULL,
		[MakerId] INT NOT NULL
CONSTRAINT [PK_Models] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)	

ALTER TABLE [dbo].[Models] WITH CHECK ADD CONSTRAINT [FK_Models_Makers_MakerId] FOREIGN KEY([MakerId])
REFERENCES [dbo].[Makers] ([Id])

END
GO

-- Features
IF OBJECT_ID (N'Features', N'U') IS NULL 
BEGIN
	CREATE TABLE [dbo].[Features](
		[Id] INT IDENTITY(1,1) NOT NULL,	
		[Name] NVARCHAR(50) NOT NULL
CONSTRAINT [PK_Features] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)	

END
GO

-- Models-Features relations
IF OBJECT_ID (N'ModelsFeatures', N'U') IS NULL 
BEGIN
	CREATE TABLE [dbo].[ModelsFeatures](
		[ModelId] INT NOT NULL,
		[FeatureId] INT NOT NULL,
CONSTRAINT [PK_ModelsFeatures] PRIMARY KEY CLUSTERED 
(
	[ModelId] ASC,
	[FeatureId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[ModelsFeatures] WITH CHECK ADD CONSTRAINT [FK_ModelsFeatures_Models_ModelId] FOREIGN KEY([ModelId])
REFERENCES [dbo].[Models] ([Id])

ALTER TABLE [dbo].[ModelsFeatures] WITH CHECK ADD CONSTRAINT [FK_ModelsFeatures_Features_FeatureId] FOREIGN KEY([FeatureId])
REFERENCES [dbo].[Features] ([Id])

END
GO

-- Owners
IF OBJECT_ID (N'Owners', N'U') IS NULL 
BEGIN
	CREATE TABLE [dbo].[Owners](
		[Id] INT IDENTITY(1,1) NOT NULL,	
		[FirstName] NVARCHAR(20) NOT NULL,
		[LastName] NVARCHAR(20) NOT NULL,
		[Phone] NVARCHAR(30) NOT NULL,
		[Email] NVARCHAR(255) NOT NULL
CONSTRAINT [PK_Owners] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)	

END
GO

-- Vehicles
IF OBJECT_ID (N'Vehicles', N'U') IS NULL 
BEGIN
	CREATE TABLE [dbo].[Vehicles](
		[Id] INT IDENTITY(1,1) NOT NULL,	
		[ModelId] INT NOT NULL,
		[OwnerId] INT NOT NULL,
		[IsRegistered] BIT NOT NULL DEFAULT 0,
		[Description] NVARCHAR(MAX) NULL
CONSTRAINT [PK_Vehicles] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)	

ALTER TABLE [dbo].[Vehicles] WITH CHECK ADD CONSTRAINT [FK_Vehicles_Models_ModelId] FOREIGN KEY([ModelId])
REFERENCES [dbo].[Models] ([Id])

ALTER TABLE [dbo].[Vehicles] WITH CHECK ADD CONSTRAINT [FK_Vehicles_Owners_OwnerId] FOREIGN KEY([OwnerId])
REFERENCES [dbo].[Owners] ([Id])

END
GO

-- Photos
IF OBJECT_ID (N'Photos', N'U') IS NULL 
BEGIN
	CREATE TABLE [dbo].[Photos](
		[Id] UNIQUEIDENTIFIER NOT NULL,	
		[FileName] NVARCHAR(255) NOT NULL,
		[OriginalFileName] NVARCHAR(255) NOT NULL,
		[MimeType] NVARCHAR(255) NOT NULL,
		[VehicleId] INT NOT NULL,
CONSTRAINT [PK_Photos] PRIMARY KEY NONCLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)	

ALTER TABLE [dbo].[Photos] WITH CHECK ADD CONSTRAINT [FK_Photos_Vehicles_VehicleId] FOREIGN KEY([VehicleId])
REFERENCES [dbo].[Vehicles] ([Id])

END
GO

*/